{
    'name': 'Products Marking',
    'version': '1.0',
    'author': 'Marat Shainurov',
    'summary': 'Products Marking System',
    'sequence': -100,
    'description': "Products Marking System",
    'category': 'Sales',
    'website': 'https://github.com/Marat-Shainurov',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/product_views.xml',
        'views/warehouse_views.xml',
        'views/cost_or_income_views.xml',
        'views/prod_properties_change_act_views.xml',
        'views/marked_product_views.xml',
        'report/report.xml',
        'report/prod_properties_change_act_rep.xml'
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
